In [1]:
import pandas as pd
import plotly.graph_objects as go

In [2]:
ma_test_res = pd.read_pickle("../ma_test_res.pkl")
all_trades = pd.read_pickle("../all_trades.pkl")

In [3]:
all_trades.shape

(64171, 11)

In [ ]:
all_trades.head()

In [4]:
ma_test_res.shape

(630, 8)

In [5]:
ma_test_res.head()

,pair,num_trades,total_gain,mean_gain,min_gain,max_gain,mashort,malong
0,GBP_USD,560,-3.4,-0.006071,-93.0,128.8,4,8
1,GBP_USD,331,-648.6,-1.959517,-77.6,168.0,4,16
2,GBP_USD,292,-1070.3,-3.665411,-112.2,156.0,8,16
3,GBP_USD,205,-1246.3,-6.079512,-77.6,156.7,4,32
4,GBP_USD,166,-1313.0,-7.909639,-116.4,159.7,8,32

In [6]:
ma_test_res.columns

Index(['pair', 'num_trades', 'total_gain', 'mean_gain', 'min_gain', 'max_gain',
       'mashort', 'malong'],
      dtype='object')

In [7]:
ma_test_res = ma_test_res[['pair', 'num_trades', 'total_gain','mashort', 'malong']]

In [8]:
ma_test_res.head()

      pair  num_trades  total_gain  mashort  malong
0  GBP_USD         560        -3.4        4       8
1  GBP_USD         331      -648.6        4      16
2  GBP_USD         292     -1070.3        8      16
3  GBP_USD         205     -1246.3        4      32
4  GBP_USD         166     -1313.0        8      32

In [9]:
ma_test_res["CROSS"] = "MA_" + ma_test_res.mashort.map(str) + "_" + ma_test_res.malong.map(str)

In [10]:
ma_test_res.head()

      pair  num_trades  total_gain  mashort  malong    CROSS
0  GBP_USD         560        -3.4        4       8   MA_4_8
1  GBP_USD         331      -648.6        4      16  MA_4_16
2  GBP_USD         292     -1070.3        8      16  MA_8_16
3  GBP_USD         205     -1246.3        4      32  MA_4_32
4  GBP_USD         166     -1313.0        8      32  MA_8_32

In [11]:
df_all_gains = ma_test_res.groupby(by=["CROSS", "mashort", "malong"], as_index=False).sum()

In [12]:
df_all_gains.head()

,CROSS,mashort,malong,pair,num_trades,total_gain
0,MA_16_128,16,128,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,923,4249.2
1,MA_16_256,16,256,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,566,4999.7
2,MA_16_32,16,32,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,2913,658.0
3,MA_16_64,16,64,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1531,1227.7
4,MA_16_96,16,96,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1161,2237.7

In [13]:
df_all_gains.sort_values(by="total_gain", ascending=False, inplace=True)

In [21]:
df_all_gains.head(20)

,CROSS,mashort,malong,pair,num_trades,total_gain
21,MA_64_128,64,128,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,632,9136.7
10,MA_32_128,32,128,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,695,6920.4
5,MA_24_128,24,128,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,773,6268.9
23,MA_64_96,64,96,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,930,5899.4
11,MA_32_256,32,256,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,432,5042.0
22,MA_64_256,64,256,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,342,5022.2
6,MA_24_256,24,256,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,489,5005.3
16,MA_4_256,4,256,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1070,5005.0
26,MA_8_256,8,256,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,796,5001.5
1,MA_16_256,16,256,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,566,4999.7
0,MA_16_128,16,128,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,923,4249.2
13,MA_32_96,32,96,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,944,3814.9
8,MA_24_64,24,64,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1431,3121.4
7,MA_24_32,24,32,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,3255,3003.2
12,MA_32_64,32,64,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1365,2872.3
9,MA_24_96,24,96,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1024,2688.5
4,MA_16_96,16,96,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1161,2237.7
28,MA_8_64,8,64,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1961,1332.5
3,MA_16_64,16,64,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1531,1227.7
29,MA_8_96,8,96,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1514,787.0

In [22]:
MA_64_128 = ma_test_res[ma_test_res.CROSS=='MA_64_128'].copy()

In [34]:
MA_64_128.head(10)

        pair  num_trades  total_gain  mashort  malong      CROSS
83   GBP_JPY          26      2388.9       64     128  MA_64_128
263  EUR_JPY          18      1833.0       64     128  MA_64_128
443  CAD_JPY          28      1435.8       64     128  MA_64_128
563  NZD_JPY          28      1142.4       64     128  MA_64_128
143  GBP_CHF          22      1073.7       64     128  MA_64_128
383  USD_JPY          27      1056.4       64     128  MA_64_128
323  EUR_CHF          22       809.0       64     128  MA_64_128
623  CHF_JPY          34       708.6       64     128  MA_64_128
473  CAD_CHF          32       347.6       64     128  MA_64_128
113  GBP_NZD          27       309.9       64     128  MA_64_128

In [29]:
MA_64_128.sort_values(by="total_gain", ascending=False, inplace=True)
MA_64_128.head(20)

        pair  num_trades  total_gain  mashort  malong      CROSS
83   GBP_JPY          26      2388.9       64     128  MA_64_128
263  EUR_JPY          18      1833.0       64     128  MA_64_128
443  CAD_JPY          28      1435.8       64     128  MA_64_128
563  NZD_JPY          28      1142.4       64     128  MA_64_128
143  GBP_CHF          22      1073.7       64     128  MA_64_128
383  USD_JPY          27      1056.4       64     128  MA_64_128
323  EUR_CHF          22       809.0       64     128  MA_64_128
623  CHF_JPY          34       708.6       64     128  MA_64_128
473  CAD_CHF          32       347.6       64     128  MA_64_128
113  GBP_NZD          27       309.9       64     128  MA_64_128
53   GBP_CAD          35       254.3       64     128  MA_64_128
593  NZD_CHF          27       196.8       64     128  MA_64_128
413  USD_CHF          33        -9.8       64     128  MA_64_128
533  NZD_CAD          33       -20.4       64     128  MA_64_128
503  NZD_USD          35       -39.3       64     128  MA_64_128
173  EUR_GBP          35       -48.2       64     128  MA_64_128
233  EUR_CAD          36       -72.3       64     128  MA_64_128
23   GBP_USD          34      -270.6       64     128  MA_64_128
203  EUR_USD          34      -428.0       64     128  MA_64_128
353  USD_CAD          36      -614.2       64     128  MA_64_128

In [30]:
MA_64_128.pair.unique()

array(['GBP_JPY', 'EUR_JPY', 'CAD_JPY', 'NZD_JPY', 'GBP_CHF', 'USD_JPY',
       'EUR_CHF', 'CHF_JPY', 'CAD_CHF', 'GBP_NZD', 'GBP_CAD', 'NZD_CHF',
       'USD_CHF', 'NZD_CAD', 'NZD_USD', 'EUR_GBP', 'EUR_CAD', 'GBP_USD',
       'EUR_USD', 'USD_CAD', 'EUR_NZD'], dtype=object)

In [32]:
total_p = len(MA_64_128.pair.unique())
total_p

21

In [35]:
MA_64_128[MA_64_128.total_gain>0].shape[0]

12

In [36]:
13 / total_p

0.6190476190476191

In [20]:
for cross in df_all_gains.CROSS.unique():
    df_temp = ma_test_res[ma_test_res.CROSS==cross]
    total_p = df_temp.shape[0]
    n_good = df_temp[df_temp.total_gain>0].shape[0]
    print(f"{cross:12} {n_good:4} {(n_good/total_p)*100:4.0f}%")

MA_64_128      12   57%
MA_32_128      13   62%
MA_24_128      14   67%
MA_64_96       11   52%
MA_32_256      13   62%
MA_64_256      14   67%
MA_24_256      13   62%
MA_4_256       14   67%
MA_8_256       14   67%
MA_16_256      13   62%
MA_16_128      13   62%
MA_32_96       13   62%
MA_24_64        9   43%
MA_24_32       12   57%
MA_32_64       13   62%
MA_24_96       14   67%
MA_16_96       11   52%
MA_8_64        12   57%
MA_16_64       10   48%
MA_8_96        11   52%
MA_8_128       10   48%
MA_16_32       12   57%
MA_4_128       10   48%
MA_4_96         8   38%
MA_4_64         9   43%
MA_8_32         8   38%
MA_8_16         8   38%
MA_4_16        10   48%
MA_4_32         7   33%
MA_4_8          8   38%